/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package a3.t10.g09;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        User user = new User("John Doe", "1234567890", "", "", "", "", "");
        UserList users = new UserList();
        users.addUser(user);
        ProfileUpdateController controller = new ProfileUpdateController(user, users);
        controller.displayMenu();

    }
}
