/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package a3.t10.g09;

import java.util.Scanner;

import org.mindrot.jbcrypt.BCrypt;

public class App {
    private Client client;
    UserList userList;

    public App() {
        client = new Client();
    }

    private static void testProfileUpdateUI() {

        // Create a test user (password will be hashed in a real scenario)
        User testUser = new User(
                "test123", // idkey
                "Test User", // fullname
                "0412345678", // phone
                "test@example.com", // email
                BCrypt.hashpw("password123", BCrypt.gensalt()) // hashed password
        );
        // Add user to the list
        UserList users = new UserList();
        users.addUser(testUser);

        // Create and show the profile update controller
        ProfileUpdateController profileController = new ProfileUpdateController(testUser, users);
        profileController.displayMenu();
        /*
         * // Test each update method
         * System.out.println("Testing Profile Update UI");
         * System.out.println("1. Testing Name Update");
         * profileUI.updateName();
         * 
         * System.out.println("\n2. Testing Email Update");
         * profileUI.updateEmail();
         * 
         * System.out.println("\n3. Testing Phone Update");
         * profileUI.updatePhoneNumber();
         * 
         * System.out.println("\n4. Testing ID Key Update");
         * profileUI.updateIDKey();
         * 
         * System.out.println("\n5. Testing Password Update");
         * profileUI.updatePassword();
         * 
         * System.out.println("\nTest completed. Updated user details:");
         * System.out.println("Name: " + testUser.getFullname());
         * System.out.println("Email: " + testUser.getEmail());
         * System.out.println("Phone: " + testUser.getPhone());
         * System.out.println("ID Key: " + testUser.getIdkey());
         */
    }

    public static void main(String[] args) {
        App app = new App();
        Scanner scanner = new Scanner(System.in);
        while (true) {
            Command[] commands = app.client.getAvailableCommands();
            DisplayUIContent.printMainMenu(commands, MenuTitle.MAIN, app.client);
            if (!scanner.hasNextLine()) {
                System.out.println("No input detected. Exiting.");
                return;
            }
            String line = scanner.nextLine().trim();
            int choice;
            try {
                choice = Integer.parseInt(line);
            } catch (NumberFormatException e) {
                System.out.println("Please enter a number between 1 and " + commands.length + ".\n");
                continue;
            }
            if (choice > commands.length || choice < 1) {
                System.out.println("Invalid input. Please choose a number between 1 and " + commands.length + ".\n");
                continue;
            }
            commands[(choice - 1)].execute(scanner, app.client);
//            System.out.println("DEBUG: Command executed");
        }
    }
}
